apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: "2022-05-05T16:45:48Z"
    labels:
      app: php-helloworld
      app.kubernetes.io/component: php-helloworld
      app.kubernetes.io/instance: php-helloworld
    managedFields:
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:port:
            .: {}
            f:targetPort: {}
          f:to:
            f:kind: {}
            f:name: {}
            f:weight: {}
          f:wildcardPolicy: {}
      manager: kubectl-expose
      operation: Update
      time: "2022-05-05T16:45:48Z"
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:ingress: {}
      manager: openshift-router
      operation: Update
      time: "2022-05-05T16:45:48Z"
    name: xyz-helloworld
    namespace: ihvgxd-s2i
    resourceVersion: "39151926"
    selfLink: /apis/route.openshift.io/v1/namespaces/ihvgxd-s2i/routes/xyz-helloworld
    uid: fac4f8a5-5f9f-48e7-986b-c3af63d3340c
  spec:
    host: xyz-helloworld-ihvgxd-s2i.apps.eu46a.prod.ole.redhat.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: php-helloworld
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2022-05-05T16:45:48Z"
        status: "True"
        type: Admitted
      host: xyz-helloworld-ihvgxd-s2i.apps.eu46a.prod.ole.redhat.com
      routerCanonicalHostname: apps.eu46a.prod.ole.redhat.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
